[package]
name = "svxx_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
pedantic = "warn"

[dependencies]
dioxus = "0.4.0"
dioxus-web = "0.4.0"
